yden="MIRKLILLVLFGFMSFVANAKTIELRENNMRQIFVLHGYSASIDDHWFLDLKHQIEDEHTTVTLIPFPDSEHPDVDAWQKVLDQHIPVVNENTYFVAHSLGVITLLHFLQRHDYQKIGGMILVSGFSGPISDFSPLDAYITKSKVDTSYFHDIKKKLVYLSDNDDLVPPKLTIQLAKEIDAPYITVPNGGHFLGREGYTTFPQVVNSLKEMLESK"
print yden
length= len(yden)
print length
print (yden.lower())
low_protein = (yden.lower())
print low_protein
yden_UPPER = (low_protein.upper())
print yden_UPPER
#this is a test if git is working